#port 결정 = default 8080 = 9090
#Egiex 80 / Jenkins : 8080
server:
  port: 9090
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipe
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver 
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
# mybatis 
mybatis:
  type-aliases-package: com.sist.web.vo
  mapper-locations: mybatis/mapper/*.xml

# security 
# spring ai 
# websocket = 카프카   