server:
  port: 9090
  servlet:
    context-path: /
spring:
  #mvc = 파일업로드 
  datasource:
    postgres:
      jdbc-url: jdbc:postgresql://localhost:5432/recipe
      username: postgres
      password: 1234
      driver-class-name: org.postgresql.Driver 
    oracle:
      jdbc-url: jdbc:oracle:thin:@211.238.142.45:1521:XE
      username: hr
      password: happy
      driver-class-name: oracle.jdbc.driver.OracleDriver
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  ai:
    google:
      genai:
        api-key: ${GEN_KEY}
        embedding:
          options:
            model: gemini-embedding-001
# mybatis 
mybatis:
  type-aliases-package: com.sist.web.vo
  mapper-locations: 
   - classapth:/mapper/oracle/*.xml
   - classpath:/mapper/postgres/*.xml
  configuration:
    map-underscore-to-camel-case: true
 